### ISSUE TITLE
sra file upload results in empty file with error

### ISSUE THREAD

**Issue by najoshi** [mdshw5/sra-tools-galaxy#1]
Hi Matt,
After uploading an sra file (using Get Data) to galaxy, the file is empty and I get this error:
"The uploaded binary file contains inappropriate content"
I installed the tool from the toolshed including the dependencies.
- Nik.

**Comment by mdshw5** [comment]
Thanks, @najoshi - I'll look into this.

**Comment by mdshw5** [comment]
I've reproduced this issue ([history file](https://trello-attachments.s3.amazonaws.com/51b63354e44d25df3d003855/55207e0fd14a07ff7b6a8fe8/9627a16426d2fb691720bee0587a5204/Galaxy-History-Unnamed-history.tar.gz) and will make sure I figure out how to get this fixed. Maybe @jmchilton or @blankenberg have some insight?

![screen shot 2015-04-04 at 8 18 40 pm](https://cloud.githubusercontent.com/assets/819554/6995207/d802cea6-db07-11e4-9285-ba547aa6c225.png)

**Comment by jmchilton** [comment]
Two things - 

In your sra.py file you need to add the line 

`Binary.register_sniffable_binary_format('sra', 'sra', Sra)`

After you have defined the datatype (e.g. https://github.com/Viant-Metabolomics/Galaxy-M/blob/master/lib/galaxy/datatypes/galaxym.py).

More generally - I try to dissuade people from using the tool shed for datatypes unless they are hyper specific because I think it is kind of broken by design for datatypes - especially binary datatypes and sniff-able things. I would definitely :+1: a PR that added `sra.py` to galaxyproject/galaxy - if you were interested.

**Comment by mdshw5** [comment]
Will do both. Thanks for the advice!

**Comment by mdshw5** [comment]
Hey @najoshi - I've fixed this issue in the most recent toolshed update. Could you give it a try and see if your issue still exists?

**Comment by najoshi** [comment]
It looks like it works now. Thanks for your help!
